name: Generate and Deploy Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/unit-tests
      - feature/docs-ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Upload generated docs
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: docs/html/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/docs' || github.ref == 'refs/heads/feature/docs-ci'
    steps:
      - name: Download generated docs
        uses: actions/download-artifact@v4
        with:
          name: doxygen-docs
          path: docs/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
